# Auto Upload Script for C# Learning Notes
# This script automatically commits and pushes specified files to GitHub every 5 minutes

param(
    [string[]]$FilesToTrack = @()
)

# Function to get all lesson files
function Get-AllLessonFiles {
    # Get all files matching the pattern YYYY-MM-DD_CSharp_Lesson.md
    $lessonFiles = Get-ChildItem -Path . -Filter "*_CSharp_Lesson.md" | Where-Object {
        $_.Name -match '^\d{4}-\d{2}-\d{2}_CSharp_Lesson\.md$'
    } | Select-Object -ExpandProperty Name

    return $lessonFiles
}

# Function to get today's lesson file
function Get-TodayLessonFile {
    $today = Get-Date -Format "yyyy-MM-dd"
    $fileName = "${today}_CSharp_Lesson.md"

    if (Test-Path $fileName) {
        return $fileName
    }

    return $null
}

# Function to commit and push changes for a single file
function Sync-ToGitHub {
    param([string]$file)

    $timestamp = Get-Date -Format "HH:mm:ss"

    # Check if there are changes to the specific file
    git add $file
    $status = git status --porcelain $file

    if ($status) {
        Write-Host "[$timestamp] Changes detected in $file - committing and pushing..." -ForegroundColor Green

        $commitMsg = @"
Update file: $file

Automated update of C# learning progress.
File: $file
Timestamp: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

🤖 Generated by csharp_prof
"@

        git commit -m $commitMsg
        git push origin main

        if ($LASTEXITCODE -eq 0) {
            Write-Host "[$timestamp] Successfully pushed $file to GitHub!" -ForegroundColor Cyan
        } else {
            Write-Host "[$timestamp] Error pushing $file to GitHub" -ForegroundColor Red
        }
    } else {
        Write-Host "[$timestamp] No changes detected in $file" -ForegroundColor Gray
    }
}

# --- Main script ---
Write-Host "==================================================" -ForegroundColor Magenta
Write-Host "C# Learning Auto-Upload Agent Started" -ForegroundColor Magenta
Write-Host "==================================================" -ForegroundColor Magenta
Write-Host ""

# Determine which files to monitor
if ($FilesToTrack.Count -eq 0) {
    Write-Host "No specific files provided. Auto-detecting all lesson files..." -ForegroundColor Yellow

    # Get all lesson files (past and present)
    $allLessonFiles = Get-AllLessonFiles
    if ($allLessonFiles.Count -gt 0) {
        $FilesToTrack += $allLessonFiles
        Write-Host "Found $($allLessonFiles.Count) lesson file(s)" -ForegroundColor Green
    }

    if ($FilesToTrack.Count -eq 0) {
        Write-Host "ERROR: No lesson files found. Looking for files matching pattern: YYYY-MM-DD_CSharp_Lesson.md" -ForegroundColor Red
        Write-Host "Usage: .\auto_upload.ps1 -FilesToTrack 'file1.md', 'file2.md'" -ForegroundColor Yellow
        exit 1
    }
}

Write-Host "Tracking the following files:" -ForegroundColor Green
$FilesToTrack | ForEach-Object { Write-Host "- $_" }
Write-Host ""
Write-Host "Upload interval: 5 minutes" -ForegroundColor Green
Write-Host "Press Ctrl-C to stop the agent" -ForegroundColor Yellow
Write-Host ""

# Main loop
$uploadCount = 0
while ($true) {
    try {
        $uploadCount++
        Write-Host "--- Upload cycle #$uploadCount ---" -ForegroundColor Cyan

        foreach ($file in $FilesToTrack) {
            if (Test-Path $file) {
                Sync-ToGitHub -file $file
            } else {
                $timestamp = Get-Date -Format "HH:mm:ss"
                Write-Host "[$timestamp] File not found: $file. Skipping." -ForegroundColor Red
            }
        }

        Write-Host "Waiting 5 minutes until next sync..." -ForegroundColor Gray
        Write-Host ""

        Start-Sleep -Seconds 300  # 5 minutes

    } catch {
        Write-Host "An error occurred in the main loop: $_" -ForegroundColor Red
        Write-Host "Retrying in 1 minute..." -ForegroundColor Yellow
        Start-Sleep -Seconds 60
    }
}
